-- Create warehouse, database, and schemas for dropshipping pipeline
-- This script is idempotent and can be run multiple times safely

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
WITH 
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for dropshipping pipeline processing';

-- Create database
CREATE DATABASE IF NOT EXISTS DROPSHIPPING_DB
COMMENT = 'Database for dropshipping pipeline data';

-- Create schemas
CREATE SCHEMA IF NOT EXISTS DROPSHIPPING_DB.RAW
COMMENT = 'Raw data from Kafka events';

CREATE SCHEMA IF NOT EXISTS DROPSHIPPING_DB.STAGING
COMMENT = 'Staging area for data transformation';

CREATE SCHEMA IF NOT EXISTS DROPSHIPPING_DB.PROD
COMMENT = 'Production tables for business logic';

-- Set context
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DROPSHIPPING_DB;

-- Grant permissions (adjust as needed for your environment)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON DATABASE DROPSHIPPING_DB TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON SCHEMA DROPSHIPPING_DB.RAW TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON SCHEMA DROPSHIPPING_DB.STAGING TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON SCHEMA DROPSHIPPING_DB.PROD TO ROLE ACCOUNTADMIN;

-- Show created objects
SHOW WAREHOUSES LIKE 'COMPUTE_WH';
SHOW DATABASES LIKE 'DROPSHIPPING_DB';
SHOW SCHEMAS IN DATABASE DROPSHIPPING_DB;
